name: geopython
channels:
  - conda-forge
  - r
dependencies:
  - python=3.10
  - cython
  - jupyter
  - jupyterlab
  - geopandas
  - geoplot
  - georasters
  - matplotlib
  - networkx
  - numpy
  - openpyxl
  - pandas
  - pandas-datareader
  - plotnine
  #- numba
  - pip
  - pycountry
  - scipy
  - scikit-image 
  - scikit-learn 
  - seaborn
  - statsmodels
  - unidecode
  - wikipedia 
  - xlrd
  - pip:
    - stargazer
    - lets-plot 
    - pyfixest
