name: geopython
channels:
  - conda-forge
  - r
dependencies:
  - python=3.10
  - numpy
  - scipy
  - jupyter
  - jupyterlab
  - geopandas
  - geoplot
  - georasters
  - matplotlib
  - pandas
  - pandas-datareader
  - plotnine
  #- numba
  - pip
  - pycountry
  - statsmodels
  pip:
    - stargazer
    - lets-plot 
    - pyfixest
